service: online-bidding-api

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1
  stage: local

functions:
  app:
    handler: dist/index.handler
    events:
      - http:
          path: /api/{proxy+}
          method: any
      - http:
          path: /
          method: any

custom:
  serverless-offline:
    stage: local
    useStageVariables: false
    noPrependStageInUrl: true

plugins:
  - serverless-offline

package:
  exclude:
    - node_modules/**
    - dist/**
    - .git/**
    - .vscode/**
